### ISSUE TITLE
Features TODO list

### ISSUE THREAD

**Issue by Demindiro** [Demindiro/agreper#6]
*This list isn't complete*

These are features that will certainly be implemented.

# User features

- [ ] Search functionality
- [ ] Per user comment/thread list
- [ ] Pagination of comments for large threads
- [ ] #4 
- [ ] #11 
- [ ] Change username (in conjunction with anonymous commenting as in #4)

# Moderation features

- [x] Hide threads/comments #9 
- [ ] Mass hide/delete threads/comments
- [ ] #3 
- [ ] Move threads between forums.

# Admin features

- [ ] Custom themes
- [ ] SQL query dry run
